---
- name: Get Device Info
  hosts: switch_name
  connection: netconf
  vars:
    ansible_network_os: junipernetworks.junos.junos
  vars_prompt:
    - name: fpcNumber
      prompt: Which FPC? 
      private: no
    - name: chg_number
      prompt: Please Enter the CHG number
      private: no

  tasks:
    - name: Determine If Current Device Is Supported
      junos_command:
        commands:
        - "show version"
      register: result

    - name: Get Output
      set_fact:
        device_model: "{{ (result.stdout[0] | parse_cli_textfsm('./textfsm/device_model.textfsm'))[0].deviceModel }}"

    - name: Print Device Model
      debug:
        var: device_model

    - name: Unsupported Model
      fail: 
        msg: "Unsupported Model"
      when: device_model != "qfx10016"

    - name: Get Hardware Info
      import_tasks: GetInfo/hardware_info.yaml

    - name: Get Device Configuration
      import_tasks: GetInfo/device_config.yaml

    - name: Get BGP Groups Info
      import_tasks: GetInfo/bgp_groups_info.yaml

    - name: Generate BGP Traffic Movement Procedure
      import_tasks: Procedure/bgp_traffic_movement.yaml

    - name: Get Interfaces Info
      import_tasks: GetInfo/interfaces_info.yaml

    - name: Generate Ports Management Procedure
      import_tasks: Procedure/ports_management.yaml

    - name: Generate FPC Power Management Procedure
      import_tasks: Procedure/fpc_power_management.yaml

    - name: Generate FPC Power Management Procedure
      import_tasks: Procedure/fpc_power_management.yaml

    - name: Generate Plans
      import_tasks: Post/plans.yaml

    - name: Post Request
      import_tasks: Post/request.yaml
